# Generated by Django 4.2.20 on 2025-03-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportapp', '0003_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_admitted', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.academy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
